---
- name: Adding DNS server
  hosts: all
  become: yes
  tasks:
    - name: Add DNS server
      lineinfile:
        dest: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"
- name: Installing Drupal Server        
  hosts: all
  become: yes
  vars:
    jenkins_hostname: localhost
  roles:
    - geerlingguy.jenkins
