---
- name: Adding DNS server
  hosts: all
  become: yes
  tasks:
    - name: Add DNS server
      lineinfile:
        dest: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"
- name: Installing Java     
  hosts: all
  become: yes
  roles:
    - binarytemple.java
- name: Installing Jenkins
  hosts: all
  become: yes
  vars:
    jenkins_hostname: localhost
  roles:
    - binarytemple.jenkins
