---
- name: Adding DNS server
  hosts: all
  become: yes
  tasks:
    - name: Add DNS server
      lineinfile:
        dest: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"
- name: Installing Nginx Server        
  hosts: all
  become: yes
  roles:
    - {role: nginx,
       nginx_http_params: { sendfile: &quot;on&quot;,
                          access_log: &quot;/var/log/nginx/access.log&quot;},
                          nginx_sites: none }
