---
############################  Centos  ################################
# Add the components to be installed in /etc/ansible/roles/lrk.prometheus/defaults/main.yml
# prometheus_components: [prometheus]
######################################################################
- name: Adding DNS server
  hosts: all
  become: yes
  tasks:
    - name: Add DNS server
      lineinfile:
        dest: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"
- name: Install Prometheus
  hosts: all
  roles:
     - lrk.prometheus