---
- name: Adding the DNS server
  hosts: all
  become: yes
  tasks:
    - name: Add DNS server
      lineinfile:
        dest: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"
- name: Installing Tomcat Server        
  hosts: all
  become: yes
  roles:
    - telusdigital.apt-repository
    - telusdigital.java
    - telusdigital.tomcat
