---
- name: Adding DNS server
  hosts: all
  become: yes
  tasks:
    - name: Add DNS server
      lineinfile:
        dest: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"
- name: Installing and Configuring Wordpress Server        
  hosts: all
  become: yes
  roles:
    - raptas.server
    - raptas.php
    - raptas.mysql
    - raptas.wordpress
